version: "3"

services: 
    nginx:
        image: nginx:stable
        command: |
            sh -c '\
            nginx -g "daemon off;"
            '
        ports:
            - ${WEB_PORT:-10080}:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./docker/sync/log/nginx/:/var/log/nginx:delegated

    php-fpm:
        build:
            context: ./
            dockerfile: ./docker/php-fpm/Dockerfile
        command: |
            sh -c ' \
                php -v;
                /opt/remi/php74/root/usr/sbin/php-fpm && \
                tail -f -n0 /dev/null;
            '
        volumes: 
            - .:/opt/app:ro
            - ./docker/php-fpm/www.conf:/etc/opt/remi/php74/php-fpm.d/www.conf:ro
            - ./docker/sync/log/php-fpm:/var/opt/remi/php74/log/php-fpm:delegated
